server:
  port: 8081

spring:
  application:
    name: auth
  profiles:
    active: local
  config:
    import:
      - optional:configserver:http://config-server.liberty52.com:8888/
  cloud:
    config:
      label: main
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:db/seed.sql