server:
  port: 8080

spring:
  application:
    name: product
  profiles:
    active: local
  config:
    import:
      - optional:configserver:http://config-server.liberty52.com:8888/
  cloud:
    config:
      label: 102-메인컨피그레이션-mariadb-연결
  output:
    ansi:
      enabled: always

logging:
  level:
    org.apache.kafka.clients.NetworkClient: off
    aws.ConfigClusterResolver: off
