name: Build and Push Docker Dev Image

on:
  push:
    branches:
      - dev
      - ci/docker-ci-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create src/main/resources/bootstrap.yml
        run: |
          mkdir -p src/main/resources
          echo "encrypt:" > src/main/resources/bootstrap.yml
          echo "  key: '${{ secrets.ENCRYPTKEY }}'" >> src/main/resources/bootstrap.yml

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GTOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build And Push Docker Dev Image
        run: |
          docker build --build-arg SPRING_PROFILES_ACTIVE=dev -t my-product-server:latest -f multistage.Dockerfile .
          docker tag my-product-server:latest ghcr.io/liberty52/liberty52-product-server:dev-v${{ github.sha }}
          docker push ghcr.io/liberty52/liberty52-product-server:dev-v${{ github.sha }}


      - name: Create Release
        if: github.ref == 'refs/heads/ci/docker-ci-pipeline'
        run: |
          RELEASE_NAME="v-$(date +'%Y.%m.%d-%H%M%S')"
          git tag "$RELEASE_NAME"
          git push origin "$RELEASE_NAME"

      - name: Clean up
        run: docker logout ghcr.io
