name: Build and Push Docker Dev Image

on:
  push:
    branches:
      - dev
      - ci/docker-ci-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create src/main/resources/bootstrap.yml
        run: |
          mkdir -p src/main/resources
          echo "encrypt:" > src/main/resources/bootstrap.yml
          echo "  key: '${{ secrets.ENCRYPTKEY }}'" >> src/main/resources/bootstrap.yml

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GTOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build And Push Docker Dev Image
        run: |
          docker build --build-arg SPRING_PROFILES_ACTIVE=dev -t my-product-server:latest -f multistage.Dockerfile .
          docker tag my-product-server:latest ghcr.io/liberty52/liberty52-product-server:dev-v${{ github.sha }}
          docker push ghcr.io/liberty52/liberty52-product-server:dev-v${{ github.sha }}


      - name: Create GitHub Release
        if: github.ref == 'refs/heads/ci/docker-ci-pipeline'
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
        run: |
          RELEASE_NAME="v-$(date +'%Y.%m.%d-%H%M%S')"
          git tag "$RELEASE_NAME"
          git push origin "$RELEASE_NAME"
          
          PREVIOUS_RELEASE=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_RELEASE" ]; then
            COMMIT_MESSAGES=$(git log --pretty=format:"- %s%n")
          else
            COMMIT_MESSAGES=$(git log --pretty=format:"- %s%n" "$PREVIOUS_RELEASE"..HEAD)
          fi
          
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"$RELEASE_NAME\",\"name\":\"$RELEASE_NAME\",\"body\":\"$COMMIT_MESSAGES\",\"draft\":false,\"prerelease\":false}"

      - name: Clean up
        run: docker logout ghcr.io
