name: '리버티 Auth 서비스 ::: CI'

on:
  pull_request:
    paths: ['liberty52-auth-service/**', 'build.gradle', '.github/workflows/liberty52-auth-service-ci.yaml', 'liberty52-common/**']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create bootstrap.yml
        env:
          SECRET_CODE: ${{ secrets.BOOTSTRAP }}
          SECRET_DIR: liberty52-auth-service/src/main/resources
          SECRET_FILE_NAME: bootstrap.yml
        run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: :liberty52-auth-service:build

